### PR TITLE
  fix binding compile due to CAPI change

### LINKED ISSUE #3594: C-API Broken on CIRCT Nightly due to Removal of Unused Argument
The Chisel C-API needs to be updated to reflect this change: https://github.com/llvm/circt/commit/55505ebcb95a6b5c2c202c3aeae7dd5c3e6bf056

This can be a PR made against the `ci/ci-circt-nightly` branch to get nightly back to green.

### PR DESCRIPTION
**Pull request by sequencer**
fix #3594

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Feature (or new API)
- API modification
- API deprecation
- Backend code generation
- Performance improvement
- Bugfix
- Documentation or website-related
- Dependency update
- Internal or build-related (includes code refactoring/cleanup)

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by sequencer** [comment]
This will pass nightly but fails in release version of CIRCT, but I think it will be fine. cc @jackkoenig

**Comment by seldridge** [comment]
I retargeted this at the ci/ci-circt-nightly staging branch. That should cause CI to now run through the _nightly_ path and use nightly CIRCT. The CI on this PR should then be green and, once merged, the nightly CI will keep the staging branch up to date (via rebase) with main. When CD kicks in, everything on the staging branch will become part of the PR to bump the CIRCT version that Chisel uses.

**Comment by jackkoenig** [comment]
With this retargeted to [ci/ci-circt-nightly](https://github.com/chipsalliance/chisel/tree/ci/ci-circt-nightly), it still seems to fail CI because the CI uses firtool 1.57.1. I'm not sure if there's anything we can do about that other than special casing PRs against `ci/ci-circt-nightly` in the `Install CIRCT`.

**Comment by sequencer** [comment]
maybe 1.57.2?

**Comment by sequencer** [comment]
For each time C-API used by Chisel changed(won't be frequently after finishing binding framework), release a minimal version of CIRCT?

**Comment by sequencer** [comment]
Got it that's nice

**Pull request merged**
