### PR TITLE
[binder] Update API `FIRRTLDirection` for CIRCT 1.60.0

### LINKED ISSUE #3629: Nightly CIRCT Failing, Panama Related
Nightly failed last night due to, assumedly C-API changes: https://github.com/chipsalliance/chisel/actions/runs/6876424861/job/18702016730

CC: @sequencer, @SpriteOvO

### PR DESCRIPTION
**Pull request by SpriteOvO**
Update API `FIRRTLDirection` for CIRCT 1.60.0

Fixes #3629.

### CODE REVIEW

**Comment by seldridge** [comment]
This looks good. Can you force push it after changing the base branch? I don't think CI is smart enough to re-run if the base branch changes. I can see about fixing that.

**Comment by SpriteOvO** [comment]
Mmm, I force-pushed but the CI still failed, and I have no idea about the error message. :/

**Comment by seldridge** [comment]
Alright, it looks like this doesn't work a fork.

**Comment by seldridge** [comment]
The problem is that this the GitHub action (I wrote) needs to know how to fetch from a fork and it doesn't. I was able to get this working by moving your branch into this repo.

**Review by seldridge — APPROVED** [review]
Thanks for getting this fixed!

**Pull request merged**
