### PR TITLE
Faster Record using HashMap and List instead of ListMap

### PR DESCRIPTION
**Pull request by tdb-alcorn**
**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

I'm opening this pull request to start a discussion. I found that when working with 1000s of elements, the Record class was bottlenecked on ListMap appends and accesses, which are both O(n), so I decided to rewrite it with HashMap and List in order to separate the concerns of storing/accessing elements and maintaining an ordering.

My question is: does Chisel want this and if so, what is the appropriate place for it? Its interface is exactly the same as Record so I think it could be a drop in replacement, but are there any other considerations that I'm not aware of?

**Release Notes**

### CODE REVIEW

**Comment by chick** [comment]
A quick perusal of this looks good. I think the thing that would be most compelling would be some scala tests that establish both the equivalence of FastRecord to Record and the performance benefit. As I suspect that most records are relatively small I think the tests should show that FastRecord does not cost appreciably more when dealing with a lot of small Record/FastRecords. I appreciate the effort here and creating a PR is the proper way to go.

Because reviewers would likely run tests using master versions of other chisel repos, it is best not to change the build.sbt, unless it is to include new dependencies.

**Comment by tdb-alcorn** [comment]
VectorMap is interesting: I think the best next step is for me to do some three-way benchmarking of existing Record vs my FastRecord vs the proposed VectorMap Record so that we can make an informed choice. I'll post my results here, then I'll push up a change to Record using whichever implementation we agree on.

**Comment by tdb-alcorn** [comment]
I've had some trouble getting the VecMap version to work (issue [here](https://github.com/mdedetrich/linked-map/issues/5)) but in the meantime here is a benchmark comparison of `Record` (with the `ListMap` implementation) and `FastRecord` (with a `HashMap` implementation).

The basic conclusion is that for records containing thousands of elements, instantiating and accessing subclasses of `FastRecord` can be ~100x faster than `Record`. I used scalameter to do the benchmarking. You can view my code at https://github.com/tdb-alcorn/chisel3/blob/faster-record/src/test/scala/chiselTests/benchmarks/RecordBench.scala

```
::Benchmark Record.instantiate::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.118929 ms
Parameters(size -> 200): 0.42843 ms
Parameters(size -> 300): 0.951674 ms
Parameters(size -> 400): 1.7646 ms
Parameters(size -> 500): 2.938924 ms
Parameters(size -> 600): 4.491057 ms
Parameters(size -> 700): 6.551844 ms
Parameters(size -> 800): 8.909523 ms
Parameters(size -> 900): 11.678474 ms
Parameters(size -> 1000): 14.82363 ms
Parameters(size -> 1100): 17.935291 ms
Parameters(size -> 1200): 19.82534 ms
Parameters(size -> 1300): 24.449814 ms
Parameters(size -> 1400): 30.520406 ms
Parameters(size -> 1500): 35.277707 ms
Parameters(size -> 1600): 37.300183 ms
Parameters(size -> 1700): 41.692569 ms
Parameters(size -> 1800): 47.61216 ms
Parameters(size -> 1900): 51.246062 ms
Parameters(size -> 2000): 57.217878 ms

::Benchmark Record.getElements::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.050009 ms
Parameters(size -> 200): 0.046876 ms
Parameters(size -> 300): 0.048837 ms
Parameters(size -> 400): 0.051499 ms
Parameters(size -> 500): 0.059697 ms
Parameters(size -> 600): 0.063633 ms
Parameters(size -> 700): 0.048449 ms
Parameters(size -> 800): 0.051985 ms
Parameters(size -> 900): 0.058428 ms
Parameters(size -> 1000): 0.066414 ms
Parameters(size -> 1100): 0.069433 ms
Parameters(size -> 1200): 0.076144 ms
Parameters(size -> 1300): 0.084952 ms
Parameters(size -> 1400): 0.092883 ms
Parameters(size -> 1500): 0.10015 ms
Parameters(size -> 1600): 0.106893 ms
Parameters(size -> 1700): 0.11489 ms
Parameters(size -> 1800): 0.097452 ms
Parameters(size -> 1900): 0.124243 ms
Parameters(size -> 2000): 0.136673 ms

::Benchmark Record.random access::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.045968 ms
Parameters(size -> 200): 0.090696 ms
Parameters(size -> 300): 0.15554 ms
Parameters(size -> 400): 0.210501 ms
Parameters(size -> 500): 0.27948 ms
Parameters(size -> 600): 0.340576 ms
Parameters(size -> 700): 0.477423 ms
Parameters(size -> 800): 0.540005 ms
Parameters(size -> 900): 0.650997 ms
Parameters(size -> 1000): 0.818038 ms
Parameters(size -> 1100): 0.914869 ms
Parameters(size -> 1200): 0.967714 ms
Parameters(size -> 1300): 1.16198 ms
Parameters(size -> 1400): 1.331131 ms
Parameters(size -> 1500): 1.556299 ms
Parameters(size -> 1600): 1.640306 ms
Parameters(size -> 1700): 1.83949 ms
Parameters(size -> 1800): 1.967308 ms
Parameters(size -> 1900): 1.703609 ms
Parameters(size -> 2000): 2.595584 ms

::Benchmark FastRecord.instantiate::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.040242 ms
Parameters(size -> 200): 0.081636 ms
Parameters(size -> 300): 0.123285 ms
Parameters(size -> 400): 0.165962 ms
Parameters(size -> 500): 0.208891 ms
Parameters(size -> 600): 0.253065 ms
Parameters(size -> 700): 0.294956 ms
Parameters(size -> 800): 0.340058 ms
Parameters(size -> 900): 0.385455 ms
Parameters(size -> 1000): 0.431545 ms
Parameters(size -> 1100): 0.478273 ms
Parameters(size -> 1200): 0.526268 ms
Parameters(size -> 1300): 0.574485 ms
Parameters(size -> 1400): 0.623341 ms
Parameters(size -> 1500): 0.672522 ms
Parameters(size -> 1600): 0.720188 ms
Parameters(size -> 1700): 0.769885 ms
Parameters(size -> 1800): 0.820368 ms
Parameters(size -> 1900): 0.868805 ms
Parameters(size -> 2000): 1.046963 ms

::Benchmark FastRecord.getElements::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.026452 ms
Parameters(size -> 200): 0.047791 ms
Parameters(size -> 300): 0.059839 ms
Parameters(size -> 400): 0.080591 ms
Parameters(size -> 500): 0.102596 ms
Parameters(size -> 600): 0.121022 ms
Parameters(size -> 700): 0.097364 ms
Parameters(size -> 800): 0.106369 ms
Parameters(size -> 900): 0.087101 ms
Parameters(size -> 1000): 0.098406 ms
Parameters(size -> 1100): 0.110639 ms
Parameters(size -> 1200): 0.120197 ms
Parameters(size -> 1300): 0.128573 ms
Parameters(size -> 1400): 0.138541 ms
Parameters(size -> 1500): 0.149162 ms
Parameters(size -> 1600): 0.159744 ms
Parameters(size -> 1700): 0.169538 ms
Parameters(size -> 1800): 0.172671 ms
Parameters(size -> 1900): 0.18293 ms
Parameters(size -> 2000): 0.191635 ms

::Benchmark FastRecord.random access::
cores: 8
hostname: xps
name: OpenJDK 64-Bit Server VM
osArch: amd64
osName: Linux
vendor: Oracle Corporation
version: 25.181-b13
Parameters(size -> 100): 0.016693 ms
Parameters(size -> 200): 0.018932 ms
Parameters(size -> 300): 0.01999 ms
Parameters(size -> 400): 0.016834 ms
Parameters(size -> 500): 0.017043 ms
Parameters(size -> 600): 0.017703 ms
Parameters(size -> 700): 0.018239 ms
Parameters(size -> 800): 0.018698 ms
Parameters(size -> 900): 0.018715 ms
Parameters(size -> 1000): 0.018938 ms
Parameters(size -> 1100): 0.018718 ms
Parameters(size -> 1200): 0.019256 ms
Parameters(size -> 1300): 0.020009 ms
Parameters(size -> 1400): 0.019253 ms
Parameters(size -> 1500): 0.020378 ms
Parameters(size -> 1600): 0.020041 ms
Parameters(size -> 1700): 0.020727 ms
Parameters(size -> 1800): 0.020598 ms
Parameters(size -> 1900): 0.021496 ms
Parameters(size -> 2000): 0.020847 ms
```

**Comment by tdb-alcorn** [comment]
I'm into the SeqMap idea but can't figure out how to test it. Maybe we should run with hashmap for now and revisit seqmap when Scala 2.13 is released?

**Comment by jackkoenig** [comment]
This should be resolved by the addition of Scala 2.13. I want to check this with your benchmark before closing this PR though.

**Comment by jackkoenig** [comment]
Fixed by using VectorMap in 2.13.

**Pull request closed without merging**
