### PR TITLE
set sample_element's probeInfo for Vecs

### PR DESCRIPTION
**Pull request by debs-sifive**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

For `Vec`s, also set the `probeInfo` of their `sample_element`, which is used to determine its element type.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Review by azidar — APPROVED** [review]
While I approve, i'd like to see a test case that covers this error.

**Comment by dtzSiFive** [comment]
Can you add a test to check this works as intended and continues to? Thanks!

**Comment by debs-sifive** [comment]
Working on it! Accidentally merged too early, so it will be coming in a separate PR.

**Comment by debs-sifive** [comment]
OK actually after talking with Adam more, the `sample_element` issue no longer affects the FIRRTL that gets emitted — we were only seeing it before with the probe aggregate-blasting approach because that required probe modifiers to get nested inside of Vecs, which no longer happens/is legal to get emitted.

So it's not something we can detect anymore in the emitted firrtl... that said, I think we should keep this fix in place because it makes sense for the `sample_element` to have the same probe information to the actual vector elements in case it gets used down the line. Which I know is not going to be super satisfying b/c of this whole "source of truth" on the vector element type getting mutated in this random place :(

**Pull request merged**
