### PR TITLE
Make Property an Element.

### PR DESCRIPTION
**Pull request by mikeurbach**
### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Internal or build-related (includes code refactoring/cleanup)

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

This is the right place in the Chisel type hierarchy for Property as it exists today. Property types can be used in Aggregates, and are not themselves Aggregates in their current form. Making Property extend Element allows much of Chisel's internal reflection to work as expected when Property types are used in Aggregates.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by mikeurbach** [comment]
I wasn't sure if this should be marked "internal" or something else...

Also, I wasn't sure how this should be documented. The docs for Data Types and Bundles and Vecs don't really mention Element. I can add something to the Property docs if that makes sense.

**Comment by jackkoenig** [comment]
> I wasn't sure if this should be marked "internal" or something else...

Technically it's an API change, I'm not sure if we want to report it as such though since Property has not been released in an official version, we could just mark it "no release notes"

**Comment by mikeurbach** [comment]
Not marking it an API change since we haven't release Properties makes sense. I sort of like being able to at least mention it in the release notes, so is "Internal" reasonable for that? I can also use "No Release Notes" if that's better.

**Comment by jackkoenig** [comment]
Internal is good for that 👍

**Pull request merged**
