### PR TITLE
Fix BoringUtils.bore can not bore from a Probe

### PR DESCRIPTION
**Pull request by sequencer**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by jackkoenig** [comment]
@debs-sifive @dtzSiFive can one of you review this?

I also changed the Milestone to 6.0 since Probes are new in 6.0.

**Review by debs-sifive — APPROVED** [review]

**Review by dtzSiFive — COMMENTED** [review]
Looks reasonable to me, we support this in CIRCT (internally, can't annotate probes) although I haven't dove into the equivalent code here too carefully-- is the sink expected to also be a probe? (and if drilling input ports, are the various combinations handled sanely?)

Please add a test demonstrating this and expected behavior for at least one scenario.

**Comment by sequencer** [comment]
> is the sink expected to also be a probe? (and if drilling input ports, are the various combinations handled sanely?)

Yes sink should be a probe, Since input probe is forbidden in CIRCT, the LCA module should be the module that sink signal in.

**Comment by sequencer** [comment]
(Cleaning my backlogs) I'll add test tomorrow.

**Comment by dtzSiFive** [comment]
Awesome, thanks! :+1:

**Comment by sequencer** [comment]
Sorry for the **tomorrow**

**Pull request merged**
