### PR TITLE
Longer path info

### PR DESCRIPTION
**Pull request by azidar**
**Related issue**: 

**Type of change**: bug report | feature request | documentation | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification

**Development Phase**: proposal |  implementation

**Release Notes**

### CODE REVIEW

**Comment by mwachs5** [comment]
does this give you the full(er)  file path instead of just the Foo.scala?

**Comment by seldridge** [comment]
@mwachs5: My read of this is that if `/scala/` exists in source locator, you'll get everything after that. So instead of `Foo.scala`, the info would be `packag/subpackage/Foo.scala`.

If `/scala/` doesn't exist, then you'll just get the full path.

**Comment by mwachs5** [comment]
hmm, but I guess if you have some things in rocket-chip/src/main/scala/utils/Foo.scala and (hypothetical) chisel3/src/main/scala/utils/Foo.scala, both would just say "utils/Foo.scala"

**Comment by seldridge** [comment]
Good point. I think I'm in favor of making the full path available to enable things like underlining the problematic code---something like https://github.com/freechipsproject/firrtl/issues/1598.

**Comment by jackkoenig** [comment]
Fixed by https://github.com/chipsalliance/chisel/pull/2791

**Pull request closed without merging**
