### PR TITLE
Remove Map and Tuple property types.

### PR DESCRIPTION
**Pull request by mikeurbach**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- API modification

#### Desired Merge Strategy

- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes

These property types weren't necessary in the end. A Map can easily be represented by a list of object with two fields, and this is how it's been done downstream. Similarly, a Tuple can easily be represented by an object with two fields, and this is how it's been done downstream. Remove these to simplify Chisel and reduce maintainence burden.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [x] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [x] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by mikeurbach** [comment]
@seldridge here's the other half of removing this, if you care to take a look. FIRRTL parser never seemed to support properties as far as I can tell.

**Review by seldridge — APPROVED** [review]
LGTM as far as this is removing an unused feature.

I didn't realize that the aptly named `Boilerplate` existed. Nice to see simplification where possible. Thanks for not letting this linger...

**Comment by sequencer** [comment]
🫠I was fighting with it last night.

**Comment by mikeurbach** [comment]
@sequencer since you've had your hands on it, what do you think about removing Map and Tuple? My thought is it is simpler to have just Class and Seq. You can add a user-defined Tuple type with two output properties for name and value, and a user defined Map type that is a sequence of tuple objects.

**Comment by sequencer** [comment]
> @sequencer since you've had your hands on it, what do you think about removing Map and Tuple? My thought is it is simpler to have just Class and Seq. You can add a user-defined Tuple type with two output properties for name and value, and a user defined Map type that is a sequence of tuple objects.

I do agree with it. Basically what Property does is capturing Scala type in typeclass, restore them in Firrtl, and expose them in the OM. At least from my part(not as intensive as SiFive does), I only nedd basic type plus a simple aggregate type. This does simplify the C-API designing as well as the type challenge in Scala.

**Pull request merged**
