### PR TITLE
[CI] jextract, adopt: 20 -> 21

### PR DESCRIPTION
**Pull request by dtzSiFive**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Dependency update
- Internal or build-related (includes code refactoring/cleanup)

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by dtzSiFive** [comment]
Last night's CI failed trying to grab jextract 20: https://github.com/chipsalliance/chisel/actions/runs/6311071188/job/17134348465 .

Looking at https://jdk.java.net/jextract/ the latest is 21, although there's a special page for 19 that maybe is more likely to stick around (?) ?

Didn't look much into why 20 disappeared, especially since these are "early access" builds.

**Comment by sequencer** [comment]
https://github.com/chipsalliance/chisel/blob/2be8bbc1d4bb4425a9db6edb0fee9c08502ab57b/.github/workflows/test.yml#L91
Should be upgraded as well.

**Comment by dtzSiFive** [comment]
Done! Although unfortunately new error: https://github.com/chipsalliance/chisel/actions/runs/6313202496/job/17140770653?pr=3551 

>    Error: Could not find satisfied version for SemVer '21'. 
  Available versions: 20.0.2+9, 20.0.1+9, 20.0.0+36, 19.0.2+7, 19.0.1+10, 19.0.0+36, 18.0.2+101, 18.0.2+9, 18.0.1+10, 18.0.0+36, 17.0.8+101, 17.0.8+7, 17.0.7+7, 17.0.6+10, 17.0.5+8, 17.0.4+101, 17.0.4+8, 17.0.3+7, 17.0.2+8, 17.0.1+12, 17.0.0+35, 16.0.2+7, 16.0.1+9, 16.0.0+36, 15.0.2+7, 15.0.1+9, 15.0.0+36, 14.0.2+12, 14.0.1+7.1, 14.0.0+36.1, 13.0.2+8.1, 13.0.1+9.1, 13.0.0+33.1, 12.0.2+10.1, 12.0.1+12, 12.0.0+33, 11.0.20+101, 11.0.20+8, 11.0.19+7, 11.0.18+10, 11.0.17+8, 11.0.16+101, 11.0.16+8, 11.0.15+10, 11.0.14+101, 11.0.14+9, 11.0.13+8, 11.0.12+7, 11.0.11+9, 11.0.10+9, 11.0.9+101, 11.0.9+11.1, 11.0.9+11, 11.0.8+10, 11.0.7+10.1, 11.0.6+10.1, 11.0.5+10.1, 11.0.4+11.1, 11.0.3+7, 11.0.2+9, 11.0.2+7, 11.0.1+13, 11.0.0+28, 10.0.2+13.1, 9.0.4+11, 9.0.0+181, 8.0.382+5, 8.0.372+7, 8.0.362+9, 8.0.352+8, 8.0.345+1, 8.0.342+7, 8.0.332+9, 8.0.322+6, 8.0.312+7, 8.0.302+8, 8.0.292+10, 8.0.282+8, 8.0.275+1, 8.0.272+10, 8.0.265+1, 8.0.262+10, 8.0.252+9.1, 8.0.242+8.1, 8.0.232+9.1, 8.0.222+10.1, 8.0.212+4, 8.0.212+3, 8.0.202+8, 8.0.192+12, 8.0.181+13
  
Suggestions welcome, just meant to fix a 404 (which also failed a test, but not sure I understand why) -- I'll take a closer look at some point if no one else does or knows what's going on :+1: .

**Comment by sequencer** [comment]
Sigh, 
adopt haven't release JVM 21 yet, but oracle already removed 20...

**Comment by sequencer** [comment]
Maybe try this link?
https://download.java.net/java/early_access/jextract/1/openjdk-20-jextract+1-2_linux-x64_bin.tar.gz
They seems rebuild jextract in JVM 20.

**Comment by dtzSiFive** [comment]
Great, looks like it was just temporarily down.  Closing, thanks all!

CI run since then passes: https://github.com/chipsalliance/chisel/actions/runs/6324383804

**Pull request closed without merging**
