### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by mwachs5**
Not everyone has `.` on their `$PATH`

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Documentation or website-related

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

Update Quickstart instructions for those without `.` on their `$PATH`

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.6.x`, `5.x`, or `6.x` depending on impact, API modification or big change: `7.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by schoeberl** [comment]
Why `./`? 'scala-cli' could be anywhere in your path?

**Comment by seldridge** [comment]
I agree with Martin here... this assumes that `scala-cli` is in the same directory where you have the template. I would assume that most users would follow the instructions to install `scala-cli` and put it on their `PATH`. This is what the instructions for installing `scala-cli` have the user do. After that, this command would work as-is. Making the change in this PR would _force_ users to put `scala-cli` into `.` which seems odd.

**Comment by mwachs5** [comment]
For some reason I thought that these instructions were responsible for installing scala-cli

**Comment by mwachs5** [comment]
The "for some reason" is that a reading of the line above this instruction sounds like this instruction is going to install scala-cli for you. Shouldn't we break the line up to say something like, "first install scala-cli, instructions <here>". Newline, "then get this project and run it with Scala-cli".

I apparently installed scala-cli a while back and forgot about it

**Comment by jackkoenig** [comment]
> The "for some reason" is that a reading of the line above this instruction sounds like this instruction is going to install scala-cli for you. Shouldn't we break the line up to say something like, "first install scala-cli, instructions ". Newline, "then get this project and run it with Scala-cli".

Great point. Writing good instructions is hard 😅. I'll open a PR.

**Pull request closed without merging**
