### PR TITLE
Use c++14 to pass the verilator check

### PR DESCRIPTION
**Pull request by Emin017**
When I update to verilator v5.022, the svsim test will fail (someone has already raised an [issue](https://github.com/chipsalliance/chisel/issues/3836)). I found out this was because verilator added a [check](https://github.com/verilator/verilator/commit/e3e5f30ba1b02a202aff32e10c95e824e855a6df) for the c++14 standard. 
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

Change ChiselSim to requires a C++14 compiler.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.6.x`, `5.x`, or `6.x` depending on impact, API modification or big change: `7.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Review by seldridge — APPROVED** [review]
Generally seems fine to me. There shouldn't be an issue with requiring a compiler that supports C++14.

We haven't bumped the version of Tabby CAD OSS Suite in a while, so this likely hasn't cropped up. (We're using an older version of Verilator in CI.) We should probably do that, too, put that on latest, or add nightly/CD that tries to keep Tabby CAD up to date.

**Comment by jackkoenig** [comment]
We should merge this, but a longer term fix is we should probably make the arguments version-specific so that we can support some older Linux distros and Verilator versions out-of-the-box.

**Comment by jackkoenig** [comment]
I also wouldn't call this "No release notes", we do now require a compiler with C++14 support which should be most, but lots of users in the hardware industry are on surprisingly old Linux distros.

**Comment by seldridge** [comment]
@jackkoenig: Can we backport this and/or get this onto a non-snapshot release? I think this may be necessary for newer Verilator. I'm thinking this (https://github.com/chipsalliance/chisel-template/issues/127) is related.

**Comment by jackkoenig** [comment]
@seldridge sure, no reason not to release 6.2.0 (or 6.1.1?) with this.

**Pull request merged**
