### PR TITLE
Add Nix Flake

### PR DESCRIPTION
**Pull request by sequencer**
This PR adds `nix flake` template to setup the development environment, which can can more packages dependent by chisel. 
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.4.x`, [small] API extension: `3.5.x`, API modification or big change: `3.6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by dtzSiFive** [comment]
FWIW I maintain a circt-nix flake that is updated regularly and has pre-built binaries via cachix which might be of interest?
Whether Chisel wants to depend on that is perhaps a different question, but don't plan to stop anytime soon :+1: .

https://github.com/dtzSiFive/circt-nix

I use it for primarily for own dev environments and testing purposes (modulo free cachix limits, easy to bounce between versions, etc.  However CIRCT's recent CI efforts provide another path to that sort of thing :+1:).

**Comment by sequencer** [comment]
@dtzSiFive Sorry for the delay reply, I didn't this this.
Out team is using circt from nixpkgs, while also be the maintainer of which, would you mind upstream your version to that, so we can use the shared prebuilt circt from nixpkgs.
BTW, this will also be upstreamed to as well: https://github.com/sequencer/chisel-circt-binder/blob/f03c170f06405c2f655f223e934d4f8191b9255d/overlay.nix#L6-L38

**Comment by pineapplehunter** [comment]
Hi, I have been updating the circt package on nixpkgs for a few releases.
I have a few questions.

- Should the change in the circt package be upstream? (Shared libs?)
- Should espresso be on upstream nixpkgs?
- Is specifying the version of circt to `firtool-1.54.0` to pin the version? in that case is there any thought about caching the output? (Building the whole circt takes a lot of time)

I am happy to help with any of the packaging.

**Comment by sequencer** [comment]
> Should the change in the circt package be upstream? (Shared libs?)

Yes, shared libs is next feature that Chisel will support, FYI #3520

> Should espresso be on upstream nixpkgs?

I think so, although I have been packing it by myself in my own project, if you are willing to, 

> Is specifying the version of circt to firtool-1.54.0 to pin the version? in that case is there any thought about caching the output? (Building the whole circt takes a lot of time)

No, chisel `main` branch will bump firtool to the latest released package. Considering the build time, I think it will be good to cache each released version of CIRCT.

**Comment by pineapplehunter** [comment]
@sequencer Thanks for the reply!
> Yes, shared libs is next feature that Chisel will support, FYI https://github.com/chipsalliance/chisel/pull/3520

I will try making a PR for this on my free time.

> I think so, although I have been packing it by myself in my own project, if you are willing to,

I am happy to package if that's fine with you. BTW, is there any license for espresso? I can't seem to find it anywhere.

> No, chisel main branch will bump firtool to the latest released package. Considering the build time, I think it will be good to cache each released version of CIRCT.

Then I guess you could use the upstream version after the patch for shared libs is in nixpkgs. I think caching won't be a issue in this case.

**Comment by sequencer** [comment]
I will mark this to ready for review after 
next release of CIRCT + nixpkgs supporting sharelibs

**Comment by sequencer** [comment]
I think this is good for dev use now, it works on my aarch64-linux(asahi) and my x86-linux.
Ask for merge, `overlay.nix` in this PR will be gradually removed when patches being accepted by nixpkgs.

**Review by jackkoenig — APPROVED** [review]

**Pull request merged**
