### PR TITLE
Fix the `--mlir-print-ir-after-all` option.

### PR DESCRIPTION
**Pull request by poemonsense**
Legacy `--print-ir-after-all` has been replaced by this new argument.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

Fix the `--mlir-print-ir-after-all` option.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by poemonsense** [comment]
BTW, what's the correct way to retrieve firtool outputs when calling firtool internally via Chisel circt stage? It seems the stdout and stderr are captured by Chisel/Scala and will not produce outputs if the firtool process returns without errors.

**Comment by sequencer** [comment]
LGTM.
We need to think about how to provide a better experience to users about the CIRCT-chisel compatibility. 

CIRCT binding infrastructure is a candidate.

**Comment by poemonsense** [comment]
Though popular Chisel projects have some developers who are interested in the internal design of Chisel and CIRCT, I think Chisel is expected to provide better usability for end users without knowing the details of CIRCT and Chisel.

It would be better for Chisel to provide a pretty short list of pre-defined commands. These are like shortcuts that the users can freely use to build some minimal Chisel examples.

For advanced users, just provide them with the method to interact with firtool is enough.

Just my opinion as a Chisel user and XiangShan maintainer FYI

**Review by seldridge — APPROVED** [review]

**Comment by poemonsense** [comment]
CI failed?

**Pull request merged**
