### PR TITLE
Add const port API

### PR DESCRIPTION
**Pull request by albertchen-sifive**
### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Desired Merge Strategy

Squash

#### Release Notes

Add `IO.const` method for creating const ports.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x` or `3.6.x` depending on impact, API modification or big change: `5.0.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by albertchen-sifive** [comment]
@mikeurbach

**Review by mikeurbach — COMMENTED** [review]
Nice, this makes sense to me. I think the implementation looks good but it would be best for someone with more experience with the internals to review.

**Review by jackkoenig — CHANGES_REQUESTED** [review]
This is not valid according to the FIRRTL spec, we already have `output out : const UInt<1>`. We could add `IO.const` as a shorthand for `IO(Const(...))` but I'm not sure it's adding that much value.

**Comment by debs-sifive** [comment]
Agree with Jack. Can you check if https://github.com/chipsalliance/chisel/blob/f9f778829880effcc2e6c0724e003c404d6fc988/src/test/scala/chiselTests/ConstSpec.scala#L35 satisfies your API needs?

**Comment by albertchen-sifive** [comment]
oops didn't know this was already in. sorry for the noise

**Pull request closed without merging**
